/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 ../blender/scene.gltf 
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export default function RoomScene(props) {
  const { scene } = useGLTF("../blender/scene.gltf");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  return (
    <group {...props} dispose={null}>
      <group
        position={[0, 0, -1.412]}
        rotation={[0, -1.57, 0]}
        scale={[1, 1, 1.161]}
      >
        <mesh
          geometry={nodes.Cylinder013_Cylinder013_BlackCoatSteel.geometry}
          material={materials.BlackCoatSteel}
        />
        <mesh
          geometry={nodes.Cylinder013_Cylinder013_BlackCoatSteel_1.geometry}
          material={materials.GrayPlastic}
        />
        <mesh
          geometry={nodes.Cylinder013_Cylinder013_BlackCoatSteel_2.geometry}
          material={materials.WhiteSteelScrew}
        />
        <mesh
          geometry={nodes.Cylinder013_Cylinder013_BlackCoatSteel_3.geometry}
          material={materials.BlackPlastic}
        />
        <mesh
          geometry={nodes.Cylinder013_Cylinder013_BlackCoatSteel_4.geometry}
          material={materials.BlackWood}
        />
      </group>
      <group position={[0.867, 1.576, -1.648]} rotation={[0, -0.625, 0]}>
        <mesh
          geometry={nodes.mesh1054111511.geometry}
          material={materials.mat23}
        />
        <mesh
          geometry={nodes.mesh1054111511_1.geometry}
          material={materials.mat18}
        />
        <mesh
          geometry={nodes.mesh1054111511_2.geometry}
          material={materials.mat22}
        />
        <mesh
          geometry={nodes.mesh1054111511_3.geometry}
          material={materials.mat21}
        />
      </group>
      <group position={[0, 1.141, -1.549]}>
        <group
          position={[0, 0.02, -0.032]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={111.855}
        >
          <mesh
            geometry={nodes.Monitor1_1_1.geometry}
            material={materials.Plastic1Monitor1}
          />
          <mesh
            geometry={nodes.Monitor1_2_1.geometry}
            material={materials.Screen1Monitor1}
          />
        </group>
      </group>
      <group
        position={[-0.94, 1.188, -1.583]}
        rotation={[-Math.PI, 1.063, -Math.PI]}
        scale={0.167}
      >
        <mesh
          geometry={nodes["Node-Mesh"].geometry}
          material={materials.mat14}
        />
        <mesh
          geometry={nodes["Node-Mesh_1"].geometry}
          material={materials.mat20}
        />
        <mesh
          geometry={nodes["Node-Mesh_2"].geometry}
          material={materials["mat21.002"]}
        />
        <mesh
          geometry={nodes["Node-Mesh_3"].geometry}
          material={materials.mat10}
        />
      </group>
      <spotLight
        intensity={543.514}
        angle={Math.PI / 4}
        penumbra={0.15}
        decay={2}
        position={[0.7, 1.727, -1.372]}
        rotation={[-1.933, 0.218, 0.053]}
        target={nodes.Spot.target}
      >
        <primitive object={nodes.Spot.target} position={[0, 0, -1]} />
      </spotLight>
      <mesh
        geometry={nodes.group425587018.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group311988427.geometry}
        material={materials["mat22.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group96314515.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group449779970.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group2106755496.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1753917514.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1529968652.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group252681800.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1581414308.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group295085766.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group384612072.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group150579309.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1675960081.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group287159489.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1956214489.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group196400395.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group954813675.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group706802639.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1976194690.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1152190519.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group2074153597.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1629609685.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1030983910.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group145618305.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group826580911.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group601803475.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1589752359.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group806343109.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1238060299.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group801095923.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group418912012.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group205302596.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1323238240.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1571332333.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group34220672.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1272091893.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1899843208.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group42243725.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group2146178072.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1316349499.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1754683637.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group475225180.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group77921105.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group96968687.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group268332703.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group993315105.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1740918352.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group588539140.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group729811280.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group573547017.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1180881246.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group687259746.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group45382983.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1149852049.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group790925258.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group873458270.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group616518658.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group2085389804.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1075691498.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group2091112366.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1764140354.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1238428394.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group873558583.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1486350934.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1629393722.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1870575723.geometry}
        material={materials.mat16}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group877249531.geometry}
        material={materials.mat9}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.ComputerMouse_mesh.geometry}
        material={materials.ComputerMouse_mat1}
        position={[0.49, 0.942, -1.223]}
        rotation={[-Math.PI, -0.163, -Math.PI]}
        scale={0.032}
      />
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials["Material.002"]}
        position={[-0.011, 0, -0.001]}
        scale={[5.214, 1.068, 1.999]}
      />
      <group
        position={[0, 0, -1.412]}
        rotation={[0, -1.57, 0]}
        scale={[1, 1, 1.161]}
      >
        <mesh
          geometry={nodes.Cylinder013_Cylinder013_BlackCoatSteel_5.geometry}
          material={materials.BlackCoatSteel}
        />
        <mesh
          geometry={nodes.Cylinder013_Cylinder013_BlackCoatSteel_1_1.geometry}
          material={materials.GrayPlastic}
        />
        <mesh
          geometry={nodes.Cylinder013_Cylinder013_BlackCoatSteel_2_1.geometry}
          material={materials.WhiteSteelScrew}
        />
        <mesh
          geometry={nodes.Cylinder013_Cylinder013_BlackCoatSteel_3_1.geometry}
          material={materials.BlackPlastic}
        />
        <mesh
          geometry={nodes.Cylinder013_Cylinder013_BlackCoatSteel_4_1.geometry}
          material={materials.BlackWood}
        />
      </group>
      <group position={[0.867, 1.576, -1.648]} rotation={[0, -0.625, 0]}>
        <mesh
          geometry={nodes.mesh1054111511_4.geometry}
          material={materials.mat23}
        />
        <mesh
          geometry={nodes.mesh1054111511_1_1.geometry}
          material={materials.mat18}
        />
        <mesh
          geometry={nodes.mesh1054111511_2_1.geometry}
          material={materials.mat22}
        />
        <mesh
          geometry={nodes.mesh1054111511_3_1.geometry}
          material={materials.mat21}
        />
      </group>
      <group position={[0, 1.141, -1.549]}>
        <group
          position={[0, 0.02, -0.032]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={111.855}
        >
          <mesh
            geometry={nodes.Monitor1_1_2.geometry}
            material={materials.Plastic1Monitor1}
          />
          <mesh
            geometry={nodes.Monitor1_2_2.geometry}
            material={materials.Screen1Monitor1}
          />
        </group>
      </group>
      <group
        position={[-0.94, 1.188, -1.583]}
        rotation={[-Math.PI, 1.063, -Math.PI]}
        scale={0.167}
      >
        <mesh
          geometry={nodes["Node-Mesh_4"].geometry}
          material={materials.mat14}
        />
        <mesh
          geometry={nodes["Node-Mesh_1_1"].geometry}
          material={materials.mat20}
        />
        <mesh
          geometry={nodes["Node-Mesh_2_1"].geometry}
          material={materials["mat21.002"]}
        />
        <mesh
          geometry={nodes["Node-Mesh_3_1"].geometry}
          material={materials.mat10}
        />
      </group>
      <spotLight
        intensity={108.703}
        angle={Math.PI / 4}
        penumbra={0.15}
        decay={2}
        position={[0.7, 1.727, -1.372]}
        rotation={[-1.933, 0.218, 0.053]}
        target={nodes.Spot_2.target}
      >
        <primitive object={nodes.Spot_2.target} position={[0, 0, -1]} />
      </spotLight>
      <directionalLight
        intensity={136.6}
        // decay={2}
        position={[-10.783, 9.36, -0.001]}
        rotation={[-Math.PI / 2, 0, 0]}
        target={nodes.Sun.target}
      >
        <primitive object={nodes.Sun.target} position={[0, 0, -1]} />
      </directionalLight>
      <mesh
        geometry={nodes.group425587018_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group311988427_1.geometry}
        material={materials["mat22.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group96314515_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group449779970_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group2106755496_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1753917514_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1529968652_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group252681800_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1581414308_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group295085766_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group384612072_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group150579309_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1675960081_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group287159489_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1956214489_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group196400395_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group954813675_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group706802639_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1976194690_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1152190519_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group2074153597_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1629609685_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1030983910_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group145618305_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group826580911_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group601803475_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1589752359_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group806343109_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1238060299_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group801095923_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group418912012_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group205302596_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1323238240_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1571332333_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group34220672_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1272091893_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1899843208_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group42243725_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group2146178072_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1316349499_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1754683637_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group475225180_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group77921105_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group96968687_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group268332703_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group993315105_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1740918352_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group588539140_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group729811280_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group573547017_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1180881246_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group687259746_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group45382983_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1149852049_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group790925258_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group873458270_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group616518658_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group2085389804_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1075691498_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group2091112366_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1764140354_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1238428394_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group873558583_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1486350934_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1629393722_1.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1870575723_1.geometry}
        material={materials.mat16}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group877249531_1.geometry}
        material={materials.mat9}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.ComputerMouse_mesh_1.geometry}
        material={materials.ComputerMouse_mat1}
        position={[0.49, 0.942, -1.223]}
        rotation={[-Math.PI, -0.163, -Math.PI]}
        scale={0.032}
      />
      <mesh
        geometry={nodes.Plane_1.geometry}
        material={materials["Material.002"]}
        position={[-0.011, 0, -0.001]}
        scale={[5.214, 1.068, 1.999]}
      />
      <group
        position={[0, 0, -1.412]}
        rotation={[0, -1.57, 0]}
        scale={[1, 1, 1.161]}
      >
        <mesh
          geometry={nodes.Cylinder013_Cylinder013_BlackCoatSteel_6.geometry}
          material={materials.BlackCoatSteel}
        />
        <mesh
          geometry={nodes.Cylinder013_Cylinder013_BlackCoatSteel_1_2.geometry}
          material={materials.GrayPlastic}
        />
        <mesh
          geometry={nodes.Cylinder013_Cylinder013_BlackCoatSteel_2_2.geometry}
          material={materials.WhiteSteelScrew}
        />
        <mesh
          geometry={nodes.Cylinder013_Cylinder013_BlackCoatSteel_3_2.geometry}
          material={materials.BlackPlastic}
        />
        <mesh
          geometry={nodes.Cylinder013_Cylinder013_BlackCoatSteel_4_2.geometry}
          material={materials.BlackWood}
        />
      </group>
      <group position={[0.867, 1.576, -1.648]} rotation={[0, -0.625, 0]}>
        <mesh
          geometry={nodes.mesh1054111511_5.geometry}
          material={materials.mat23}
        />
        <mesh
          geometry={nodes.mesh1054111511_1_2.geometry}
          material={materials.mat18}
        />
        <mesh
          geometry={nodes.mesh1054111511_2_2.geometry}
          material={materials.mat22}
        />
        <mesh
          geometry={nodes.mesh1054111511_3_2.geometry}
          material={materials.mat21}
        />
      </group>
      <group position={[0, 1.141, -1.549]}>
        <group
          position={[0, 0.02, -0.032]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={111.855}
        >
          <mesh
            geometry={nodes.Monitor1_1_3.geometry}
            material={materials.Plastic1Monitor1}
          />
          <mesh
            geometry={nodes.Monitor1_2_3.geometry}
            material={materials.Screen1Monitor1}
          />
        </group>
      </group>
      <group
        position={[-0.94, 1.188, -1.583]}
        rotation={[-Math.PI, 1.063, -Math.PI]}
        scale={0.167}
      >
        <mesh
          geometry={nodes["Node-Mesh_5"].geometry}
          material={materials.mat14}
        />
        <mesh
          geometry={nodes["Node-Mesh_1_2"].geometry}
          material={materials.mat20}
        />
        <mesh
          geometry={nodes["Node-Mesh_2_2"].geometry}
          material={materials["mat21.002"]}
        />
        <mesh
          geometry={nodes["Node-Mesh_3_2"].geometry}
          material={materials.mat10}
        />
      </group>
      <spotLight
        intensity={108.703}
        angle={Math.PI / 4}
        penumbra={0.15}
        decay={2}
        position={[0.7, 1.727, -1.372]}
        rotation={[-1.933, 0.218, 0.053]}
        target={nodes.Spot_4.target}
      >
        <primitive object={nodes.Spot_4.target} position={[0, 0, -1]} />
      </spotLight>
      <directionalLight
        intensity={136.6}
        // decay={2}
        position={[-10.783, 9.36, -0.001]}
        rotation={[-Math.PI / 2, 0, 0]}
        target={nodes.Sun_2.target}
      >
        <primitive object={nodes.Sun_2.target} position={[0, 0, -1]} />
      </directionalLight>
      <mesh
        geometry={nodes.group425587018_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group311988427_2.geometry}
        material={materials["mat22.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group96314515_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group449779970_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group2106755496_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1753917514_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1529968652_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group252681800_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1581414308_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group295085766_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group384612072_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group150579309_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1675960081_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group287159489_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1956214489_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group196400395_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group954813675_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group706802639_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1976194690_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1152190519_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group2074153597_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1629609685_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1030983910_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group145618305_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group826580911_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group601803475_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1589752359_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group806343109_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1238060299_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group801095923_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group418912012_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group205302596_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1323238240_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1571332333_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group34220672_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1272091893_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1899843208_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group42243725_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group2146178072_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1316349499_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1754683637_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group475225180_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group77921105_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group96968687_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group268332703_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group993315105_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1740918352_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group588539140_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group729811280_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group573547017_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1180881246_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group687259746_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group45382983_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1149852049_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group790925258_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group873458270_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group616518658_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group2085389804_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1075691498_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group2091112366_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1764140354_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1238428394_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group873558583_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1486350934_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1629393722_2.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1870575723_2.geometry}
        material={materials.mat16}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group877249531_2.geometry}
        material={materials.mat9}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.ComputerMouse_mesh_2.geometry}
        material={materials.ComputerMouse_mat1}
        position={[0.49, 0.942, -1.223]}
        rotation={[-Math.PI, -0.163, -Math.PI]}
        scale={0.032}
      />
      <mesh
        geometry={nodes.Plane_2.geometry}
        material={materials["Material.002"]}
        position={[-0.011, 0, -0.001]}
        scale={[5.214, 1.068, 1.999]}
      />
      <group
        position={[0, 0, -1.412]}
        rotation={[0, -1.57, 0]}
        scale={[1, 1, 1.161]}
      >
        <mesh
          geometry={nodes.Cylinder013_Cylinder013_BlackCoatSteel_7.geometry}
          material={materials.BlackCoatSteel}
        />
        <mesh
          geometry={nodes.Cylinder013_Cylinder013_BlackCoatSteel_1_3.geometry}
          material={materials.GrayPlastic}
        />
        <mesh
          geometry={nodes.Cylinder013_Cylinder013_BlackCoatSteel_2_3.geometry}
          material={materials.WhiteSteelScrew}
        />
        <mesh
          geometry={nodes.Cylinder013_Cylinder013_BlackCoatSteel_3_3.geometry}
          material={materials.BlackPlastic}
        />
        <mesh
          geometry={nodes.Cylinder013_Cylinder013_BlackCoatSteel_4_3.geometry}
          material={materials.BlackWood}
        />
      </group>
      <group position={[0.867, 1.576, -1.648]} rotation={[0, -0.625, 0]}>
        <mesh
          geometry={nodes.mesh1054111511_6.geometry}
          material={materials.mat23}
        />
        <mesh
          geometry={nodes.mesh1054111511_1_3.geometry}
          material={materials.mat18}
        />
        <mesh
          geometry={nodes.mesh1054111511_2_3.geometry}
          material={materials.mat22}
        />
        <mesh
          geometry={nodes.mesh1054111511_3_3.geometry}
          material={materials.mat21}
        />
      </group>
      <group position={[0, 1.141, -1.549]}>
        <group
          position={[0, 0.02, -0.032]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={111.855}
        >
          <mesh
            geometry={nodes.Monitor1_1_4.geometry}
            material={materials.Plastic1Monitor1}
          />
          <mesh
            geometry={nodes.Monitor1_2_4.geometry}
            material={materials.Screen1Monitor1}
          />
        </group>
      </group>
      <group
        position={[-0.94, 1.188, -1.583]}
        rotation={[-Math.PI, 1.063, -Math.PI]}
        scale={0.167}
      >
        <mesh
          geometry={nodes["Node-Mesh_6"].geometry}
          material={materials.mat14}
        />
        <mesh
          geometry={nodes["Node-Mesh_1_3"].geometry}
          material={materials.mat20}
        />
        <mesh
          geometry={nodes["Node-Mesh_2_3"].geometry}
          material={materials["mat21.002"]}
        />
        <mesh
          geometry={nodes["Node-Mesh_3_3"].geometry}
          material={materials.mat10}
        />
      </group>
      <spotLight
        intensity={108.703}
        angle={Math.PI / 4}
        penumbra={0.15}
        decay={2}
        position={[0.7, 1.727, -1.372]}
        rotation={[-1.933, 0.218, 0.053]}
        target={nodes.Spot_6.target}
      >
        <primitive object={nodes.Spot_6.target} position={[0, 0, -1]} />
      </spotLight>
      <mesh
        geometry={nodes.group425587018_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group311988427_3.geometry}
        material={materials["mat22.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group96314515_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group449779970_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group2106755496_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1753917514_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1529968652_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group252681800_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1581414308_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group295085766_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group384612072_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group150579309_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1675960081_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group287159489_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1956214489_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group196400395_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group954813675_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group706802639_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1976194690_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1152190519_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group2074153597_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1629609685_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1030983910_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group145618305_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group826580911_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group601803475_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1589752359_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group806343109_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1238060299_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group801095923_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group418912012_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group205302596_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1323238240_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1571332333_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group34220672_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1272091893_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1899843208_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group42243725_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group2146178072_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1316349499_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1754683637_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group475225180_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group77921105_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group96968687_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group268332703_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group993315105_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1740918352_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group588539140_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group729811280_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group573547017_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1180881246_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group687259746_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group45382983_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1149852049_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group790925258_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group873458270_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group616518658_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group2085389804_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1075691498_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group2091112366_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1764140354_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1238428394_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group873558583_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1486350934_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1629393722_3.geometry}
        material={materials["mat21.001"]}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group1870575723_3.geometry}
        material={materials.mat16}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.group877249531_3.geometry}
        material={materials.mat9}
        position={[0, 0.958, -1.172]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.ComputerMouse_mesh_3.geometry}
        material={materials.ComputerMouse_mat1}
        position={[0.49, 0.942, -1.223]}
        rotation={[-Math.PI, -0.163, -Math.PI]}
        scale={0.032}
      />
      <mesh
        geometry={nodes.Plane_3.geometry}
        material={materials["Material.002"]}
        position={[-0.011, 0, -0.001]}
        scale={[5.214, 1.068, 1.999]}
      />
    </group>
  );
}

useGLTF.preload("/scene.gltf");
